[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.36", features = ["derive"] }
quinn = "0.11.7"
rustls = { version = "0.23.25", features = ["aws-lc-rs"] }
tokio = { version = "1.44.1", features = ["io-std", "io-util", "macros", "rt", "rt-multi-thread", "signal"] }
common = { path = "../common"}
futures = "0.3.31"
zstd = "0.13.3"

[[bin]]
name = "qsync_client"
path = "src/main.rs"
